--liquibase formatted sql

--changeset jsegarradev:001_create_dummy
-- Walking-skeleton table. `value` is a reserved word, so the column is `dummy_value` (springboot.md §7).
-- IDENTITY is portable across the H2 (PostgreSQL-mode) stand-in and PostgreSQL.
CREATE TABLE dummy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dummy_value VARCHAR(255) NOT NULL
);
--rollback DROP TABLE dummy;
